name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2 — Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Step 3 — Upload project files
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."

      # Step 4 — Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
